In [1]:
import pandas as pd

In [2]:
lag_target_df = pd.read_excel('data/lag_and_target.xlsx', sheet_name='DATA')
lag_target_df

     Year  Quarter    First  Second   Third  Most_Recent
0    1965        3   6.7731  7.1522  7.1522      10.8806
1    1965        4   7.9135  9.5383  9.5383      12.6215
2    1966        1  10.0542  9.9310  9.9310      12.9154
3    1966        2   6.1259  6.3000  6.3000       4.7577
4    1966        3   7.6959  6.8897  6.8897       7.4544
..    ...      ...      ...     ...     ...          ...
228  2022        3   6.7352  7.3304  7.7469       7.2399
229  2022        4   6.5066  6.7105  6.5963       6.5211
230  2023        1   5.1132  5.4377  6.1320       6.2801
231  2023        2   4.6816  4.1148  3.7727       3.7727
232  2023        3   8.5453  8.8758  8.3348       8.3348

[233 rows x 6 columns]

In [3]:
NGDP_mean_df = pd.read_excel('data/MeanMedian_NGDP_Growth.xlsx', sheet_name='Mean_Growth')
NGDP_mean_df.rename(columns={"DNGDP2": "DNGDP2_mean", "DNGDP3": "DNGDP3_mean","DNGDP4": "DNGDP4_mean","DNGDP5": "DNGDP5_mean","DNGDP6": "DNGDP6_mean"}, inplace=True)
NGDP_mean_df

,YEAR,QUARTER,DNGDP2_mean,DNGDP3_mean,DNGDP4_mean,DNGDP5_mean,DNGDP6_mean
0,1968,4,6.5146,5.4229,5.5691,6.7676,7.1207
1,1969,1,5.9047,5.1511,6.2610,6.6314,NaN
2,1969,2,6.2843,5.8472,5.1182,5.4166,NaN
3,1969,3,6.1014,5.1897,4.6871,5.1882,NaN
4,1969,4,4.9263,4.0534,3.9902,6.1504,6.9360
...,...,...,...,...,...,...,...
216,2022,4,5.3699,4.2738,3.7015,4.0092,4.4493
217,2023,1,3.4952,3.2901,3.5346,3.8600,4.0222
218,2023,2,3.8540,3.0703,3.3725,3.7997,4.1012
219,2023,3,4.6345,3.8417,3.4664,3.8039,4.2266
220,2023,4,4.3221,3.8916,3.8955,4.4764,4.2485

In [4]:
NGDP_median_df = pd.read_excel('data/MeanMedian_NGDP_Growth.xlsx', sheet_name='Median_Growth')
NGDP_median_df.rename(columns={"DNGDP2": "DNGDP2_median", "DNGDP3": "DNGDP3_median","DNGDP4": "DNGDP4_median","DNGDP5": "DNGDP5_median","DNGDP6": "DNGDP6_median"}, inplace=True)
NGDP_median_df

,YEAR,QUARTER,DNGDP2_median,DNGDP3_median,DNGDP4_median,DNGDP5_median,DNGDP6_median
0,1968,4,6.5861,5.0652,5.9311,7.2288,6.6460
1,1969,1,5.9857,4.9736,6.2832,7.0926,NaN
2,1969,2,6.3473,5.7924,5.7097,4.7482,NaN
3,1969,3,6.1929,4.7688,5.1492,5.0837,NaN
4,1969,4,4.7482,4.6925,4.2100,6.2973,6.6231
...,...,...,...,...,...,...,...
216,2022,4,5.8005,4.0350,3.1805,3.6657,3.7287
217,2023,1,4.0234,3.3772,3.4598,3.8538,4.2120
218,2023,2,4.0374,3.2651,3.1981,4.0284,3.8241
219,2023,3,4.6608,3.6710,3.8699,3.1410,4.2378
220,2023,4,4.1227,3.1954,4.1864,4.0461,3.8621

In [5]:
RGDP_mean_df = pd.read_excel('data/MeanMedian_RGDP_Growth.xlsx', sheet_name='Mean_Growth')
RGDP_mean_df.rename(columns={"RGDP2": "RGDP2_mean", "RGDP3": "RGDP3_mean","RGDP4": "RGDP4_mean","RGDP5": "RGDP5_mean","RGDP6": "RGDP6_mean"}, inplace=True)
RGDP_mean_df

     YEAR  QUARTER  RGDP2_mean  RGDP3_mean  RGDP4_mean  RGDP5_mean  RGDP6_mean
0    1968        4    717.4881    721.3801    726.1421    733.1697    740.8253
1    1969        1    722.0681    726.5384    732.3057    739.4411         NaN
2    1969        2    728.0635    732.3149    736.7007    741.7566         NaN
3    1969        3    730.6541    733.6577    736.0982    740.4814         NaN
4    1969        4    731.0989    731.0317    731.6208    736.2154    742.7392
..    ...      ...         ...         ...         ...         ...         ...
216  2022        4  20072.4360  20102.9056  20125.4076  20148.9966  20237.4107
217  2023        1  20225.7811  20248.9528  20275.4800  20339.4748  20423.5320
218  2023        2  20278.4101  20292.1268  20324.3098  20396.2924  20486.5739
219  2023        3  20494.7658  20549.9548  20588.9488  20659.8204  20750.1991
220  2023        4  22553.6177  22614.1946  22682.2572  22784.6394  22894.5627

[221 rows x 7 columns]

In [6]:
RGDP_median_df = pd.read_excel('data/MeanMedian_RGDP_Growth.xlsx', sheet_name='Median_Growth')
RGDP_median_df.rename(columns={"RGDP2": "RGDP2_median", "RGDP3": "RGDP3_median","RGDP4": "RGDP4_median","RGDP5": "RGDP5_median","RGDP6": "RGDP6_median"}, inplace=True)
RGDP_median_df

,YEAR,QUARTER,RGDP2_median,RGDP3_median,RGDP4_median,RGDP5_median,RGDP6_median
0,1968,4,718.5484,721.6000,725.6000,733.3333,740.6250
1,1969,1,721.6000,725.8065,731.7460,739.3701,NaN
2,1969,2,727.7778,733.0709,737.5000,740.3101,NaN
3,1969,3,730.2326,733.5897,736.1538,740.6136,NaN
4,1969,4,731.2977,731.8182,732.8244,737.3134,742.9630
...,...,...,...,...,...,...,...
216,2022,4,20071.5227,20080.9081,20091.9121,20135.6494,20238.3092
217,2023,1,20227.3200,20278.5648,20272.7026,20331.4440,20395.0448
218,2023,2,20285.6998,20314.1149,20311.5895,20362.0312,20486.4874
219,2023,3,20500.3365,20561.6200,20616.6071,20668.1025,20734.5316
220,2023,4,22565.0862,22609.5246,22684.6828,22766.8093,22862.1790

In [7]:
frames = [NGDP_mean_df,
          NGDP_median_df[['DNGDP2_median', 'DNGDP3_median', 'DNGDP4_median', 'DNGDP5_median', 'DNGDP6_median']],
          RGDP_mean_df[['RGDP2_mean', 'RGDP3_mean', 'RGDP4_mean', 'RGDP5_mean', 'RGDP6_mean']],
          RGDP_median_df[['RGDP2_median', 'RGDP3_median', 'RGDP4_median', 'RGDP5_median', 'RGDP6_median']]
          ]
feature_set_1_without_lag = pd.concat(frames, axis=1, )

feature_set_1_without_lag = feature_set_1_without_lag[feature_set_1_without_lag['YEAR'] >= 1989]
feature_set_1_without_lag = feature_set_1_without_lag[feature_set_1_without_lag['YEAR'] <= 2022]

feature_set_1_without_lag.to_csv('data/feature_sets/feature_set_1_without_lag.csv')
feature_set_1_without_lag

,YEAR,QUARTER,DNGDP2_mean,DNGDP3_mean,DNGDP4_mean,DNGDP5_mean,DNGDP6_mean,DNGDP2_median,DNGDP3_median,DNGDP4_median,...,RGDP2_mean,RGDP3_mean,RGDP4_mean,RGDP5_mean,RGDP6_mean,RGDP2_median,RGDP3_median,RGDP4_median,RGDP5_median,RGDP6_median
81,1989,1,8.4050,6.8171,6.3360,5.9378,5.9851,8.6009,6.3492,6.4930,...,4070.3750,4090.7500,4110.7500,4125.3125,4138.0000,4074.0000,4095.0000,4115.0000,4126.0000,4140.0000
82,1989,2,7.0945,6.3669,6.2514,6.2562,6.3195,6.4838,6.1388,5.6504,...,4106.8235,4125.9412,4142.6471,4163.8235,4177.2500,4103.0000,4119.0000,4131.0000,4153.0000,4165.5000
83,1989,3,5.9025,6.1218,6.6899,4.9941,8.8448,5.8207,5.7768,6.6341,...,4143.5133,4161.8867,4182.7333,4205.5533,4231.0267,4140.0000,4160.0000,4170.0000,4186.0000,4226.9000
84,1989,4,5.3374,5.5528,6.1549,6.2088,7.5300,5.1014,5.8167,6.8934,...,4171.5000,4187.2500,4205.8125,4229.0000,4258.0625,4169.5000,4187.5000,4204.0000,4228.5000,4253.0000
85,1990,1,5.4898,5.9550,6.4940,6.8959,6.8585,5.2726,5.5503,6.0454,...,4184.7857,4205.4286,4227.2143,4253.0714,4278.0000,4181.5000,4201.5000,4226.5000,4254.5000,4278.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,2021,4,8.5961,7.4053,6.4573,5.9745,5.4235,8.6682,7.8000,6.8957,...,19696.0509,19893.8827,20079.3760,20251.6627,20399.4464,19686.1503,19874.3933,20070.3069,20222.3504,20378.4583
213,2022,1,5.8560,7.8401,6.4712,6.0184,5.8131,6.0000,7.7273,5.9223,...,19890.2506,20088.9448,20253.7887,20405.7872,20550.0710,19892.7380,20096.5088,20243.6042,20389.5962,20533.0045
214,2022,2,7.2323,7.0835,6.2193,5.7755,5.2365,7.2941,6.3936,5.2917,...,19842.2389,19977.4708,20100.7355,20213.0454,20326.9430,19850.4600,19972.2034,20087.8952,20192.5609,20306.8044
215,2022,3,6.0054,5.6585,4.9230,4.6650,4.2993,6.6900,5.0153,5.2949,...,19743.7296,19816.7531,19877.1707,19947.0817,20023.5705,19750.2272,19811.0280,19865.8988,19937.5378,20011.5841
216,2022,4,5.3699,4.2738,3.7015,4.0092,4.4493,5.8005,4.0350,3.1805,...,20072.4360,20102.9056,20125.4076,20148.9966,20237.4107,20071.5227,20080.9081,20091.9121,20135.6494,20238.3092

In [8]:
feature_set_1_lag = lag_target_df[lag_target_df.columns[:4]]
feature_set_1_lag = feature_set_1_lag.shift(1)

feature_set_1_lag = feature_set_1_lag[feature_set_1_lag['Year'] >= 1989]
feature_set_1_lag = feature_set_1_lag[feature_set_1_lag['Year'] <= 2022]

feature_set_1_lag.to_csv('data/feature_sets/feature_set_1_lag.csv')
feature_set_1_lag

       Year  Quarter    First   Second
95   1989.0      1.0   9.7029   8.6944
96   1989.0      2.0   6.5545   7.2865
97   1989.0      3.0   5.6126   6.0700
98   1989.0      4.0   4.3096   4.3565
99   1990.0      1.0   7.7826   7.0082
..      ...      ...      ...      ...
226  2021.0      4.0  14.3327  14.6399
227  2022.0      1.0   6.4828   6.5108
228  2022.0      2.0   7.8498   8.3907
229  2022.0      3.0   6.7352   7.3304
230  2022.0      4.0   6.5066   6.7105

[136 rows x 4 columns]

In [9]:
target = lag_target_df[['Year', 'Quarter', 'Third']]

target = target[target['Year'] >= 1989]
target = target[target['Year'] <= 2022]

target.to_csv('data/target.csv')
target

     Year  Quarter    Third
94   1989        1   8.1843
95   1989        2   7.1135
96   1989        3   6.2389
97   1989        4   4.5600
98   1990        1   7.1422
..    ...      ...      ...
225  2021        4  14.5311
226  2022        1   6.5527
227  2022        2   8.4697
228  2022        3   7.7469
229  2022        4   6.5963

[136 rows x 3 columns]